version: '3.7'
services:
  db2community:
    container_name: db2community
    build: db2community 
    ports:
      - "50002:50000"
      - "55002:55000"
    env_file:
      - db2community/env_list
    privileged: true
    mem_limit: 2GB
  postgres13:
    container_name: postgres13
    build: postgres13 
    ports:
      - "5434:5432"
  # postgres13orders:
  #   container_name: postgres13orders
  #   build: postgres13orders 
  #   ports:
  #     - "5434:5432"
  cadence:
    container_name: cadence
    image: ubercadence/server:0.14.1-auto-setup
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    env_file:
      - cadence/env_list
    depends_on:
      - postgres13
  cadence-web:
    container_name: cadence-web
    image: ubercadence/web:3.18.1
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "5004:8088"
    depends_on:
      - cadence
  rabbitmq:
    container_name: rabbitmq
    build: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672